project_id = "lgwaccltpoogoukjyzke"

[functions.create-admin-user]
verify_jwt = false

[functions.energy-analysis-agent]
verify_jwt = false

[functions.energy-webhook-handler]
verify_jwt = false

[functions.pcb-design-copilot]
verify_jwt = true
